apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:latest
          ports:
            - containerPort: 8080
          env:
            - name: ADMINER_DEFAULT_SERVER
              value: "mysql-service" # Tells Adminer where the database is
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: adminer
  ports:
    - port: 80
      targetPort: 8080