# ==========================================
# 1. Main Application (default namespace)
# ==========================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hr-portal-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "local-selfsigned-issuer" # Tells Cert-Manager to secure this
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"        # Allows large file uploads
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hr-portal.local
      secretName: hr-portal-tls-secret # Cert-Manager will automatically create this secret
  rules:
    - host: hr-portal.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: spring-boot-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zelefrontend-service
                port:
                  number: 80

---
# ==========================================
# 2. Monitoring Stack (monitoring namespace)
# ==========================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: "local-selfsigned-issuer" # Tells Cert-Manager to secure this
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - grafana.hr-portal.local
        - prometheus.hr-portal.local
      secretName: monitoring-tls-secret
  rules:
    - host: grafana.hr-portal.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-grafana
                port:
                  number: 80
    - host: prometheus.hr-portal.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-kube-prometheus-prometheus
                port:
                  number: 9090

---
# ==========================================
# 3. ArgoCD Stack (argocd namespace)
# ==========================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: "local-selfsigned-issuer" # Tells Cert-Manager to secure this
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"   # ArgoCD forces HTTPS internally.This tells NGINX how to talk to it.
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - argocd.hr-portal.local
      secretName: argocd-tls-secret
  rules:
    - host: argocd.hr-portal.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
---
# ==========================================
# 4. Database GUI (default namespace)
# ==========================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adminer-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "local-selfsigned-issuer"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - db.hr-portal.local
      secretName: adminer-tls-secret
  rules:
    - host: db.hr-portal.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adminer-service
                port:
                  number: 80