## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect

server.port=8080

#spring.datasource.url =jdbc:h2:mem:testdb
#spring.datasource.username =sa
#spring.datasource.password =password
#spring.datasource.driver-class-name=org.h2.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true


# K8s Internal DNS routing to your new MySQL service
spring.datasource.url=jdbc:mysql://${DATABASE_HOST:localhost}:3306/zelledb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=zelleuser
spring.datasource.password=zellepassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Tell Hibernate to automatically create your tables  Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true

spring.cloud.compatibility-verifier.enabled=false
//spring.mvc.pathmatch.matching-strategy=ant_path_matcher

#Authentication Secret Key
jwt.secret=fiserve*123@1

#Eureka Registery Config
#eureka.client.register-with-eureka=false

#eureka.client.fetch-registry=false
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#eureka.instance.hostname=localhost
#eureka.client.service-url.defaultZone=http://localhost:8888/eureka
